In [7]:
import torch
import numpy as np
import time
import torch.nn as nn
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 4
max_iters = 1000
learning_rate = 3e-4
eval_iters = 250
dropout = 0.2

cpu


In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [9]:
text = open('/content/drive/MyDrive/wizzard_of_oz.txt', 'r').read()

In [10]:
with open('/content/drive/MyDrive/wizzard_of_oz.txt','r', encoding='utf-8') as f:
  text = f.read()
chars = sorted(set(text))
print(chars)
vocab_size = len(chars)

['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”', '•', '™']


In [11]:
string_to_int = { ch:i for i,ch in enumerate(chars)}
int_to_string = { i:ch for i,ch in enumerate(chars)}
encode = lambda s:[string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

In [12]:
data = torch.tensor(encode(text), dtype=torch.long)

In [13]:
hello_encode = encode('hello')
hello_encode

[65, 62, 69, 69, 72]

In [14]:
hello_decode = decode(hello_encode)
hello_decode

'hello'

In [15]:
%%time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()
elapse_time = end_time - start_time
print(f"{elapse_time:.8f}")

0.01307034
CPU times: user 1.38 ms, sys: 65 µs, total: 1.44 ms
Wall time: 13.3 ms


In [16]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

 0.52991748
 0.12259102


In [17]:
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [18]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])))

In [19]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [21]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [22]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [23]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [24]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])
stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))

tensor([12.7652, -5.4842,  2.0002], grad_fn=<SqueezeBackward4>)


In [26]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1,dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [27]:
# Initialize embeddings
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#Create input indices
input_indices = torch.LongTensor([1,5,3,2])

#apply embedding layer
embedded_output = embedding(input_indices)

# the output will be a tensor of shape (4,100) where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vector
print(embedded_output.shape)

torch.Size([4, 100])


In [28]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [29]:
int_64 = torch.randint(1, (3,2)).float()

float_32 = torch.rand(2,3)

result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [30]:
block_size = 8
batch_size = 4

n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
  data = train_data if split == 'train' else val_data
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i:i+block_size] for i in ix])
  x, y = x.to(device), y.to(device)
  return x, y

x, y = get_batch('train')
print("inputs:")
print(x)
print("targets:")
print(y)

inputs:
tensor([[66, 71, 64,  1, 78, 73,  1, 64],
        [71,  1, 77, 65, 62,  1, 80, 58],
        [76, 58, 66, 61,  1, 77, 65, 62],
        [77, 65, 58, 77,  1, 68, 62, 73]])
targets:
tensor([[66, 71, 64,  1, 78, 73,  1, 64],
        [71,  1, 77, 65, 62,  1, 80, 58],
        [76, 58, 66, 61,  1, 77, 65, 62],
        [77, 65, 58, 77,  1, 68, 62, 73]])


In [31]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print('when input is', context, 'target is', target)

when input is tensor([0]) target is tensor(1)
when input is tensor([0, 1]) target is tensor(1)
when input is tensor([0, 1, 1]) target is tensor(1)
when input is tensor([0, 1, 1, 1]) target is tensor(1)
when input is tensor([0, 1, 1, 1, 1]) target is tensor(48)
when input is tensor([ 0,  1,  1,  1,  1, 48]) target is tensor(65)
when input is tensor([ 0,  1,  1,  1,  1, 48, 65]) target is tensor(62)
when input is tensor([ 0,  1,  1,  1,  1, 48, 65, 62]) target is tensor(1)


In [32]:
class BigramLanguageModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

  def forward(self, index, targets=None):
    logits = self.token_embedding_table(index)
    if targets is None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)
      loss = F.cross_entropy(logits, targets)
    return logits, loss

  def generate(self, index, max_new_tokens):
    for _ in range(max_new_tokens):
      logits, loss = self.forward(index)
      logits = logits[:, -1, :]
      probs = F.softmax(logits, dim=-1)
      index_next = torch.multinomial(probs, num_samples=1)
      index = torch.cat((index, index_next), dim = 1)
    return index



In [33]:
model = BigramLanguageModel(vocab_size)
m = model.to(device)
context = torch.zeros((1,1), dtype=torch.long, device=device)

In [37]:
try:
  generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
  print(generated_chars)
except:
  print("some hacker produced error")


some hacker produced error


In [38]:
@torch.no_grad()
def estimate_loss():
  out = {}
  model.eval()
  for split in ['train','val']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      X,Y = get_batch(split)
      logits, loss = model(X,Y)
      losses[k] = loss.item()
    out[split] = losses.mean()
  model.train()
  return out

In [39]:
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

  if iter % eval_iters == 0:
    losses = estimate_loss
    print(f'step iter: {iter}, loss {losses}')

  Xb, Yb = get_batch("train")

  logits, loss = model.forward(Xb, Yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())

step iter: 0, loss <function estimate_loss at 0x7ec2e3af3520>
step iter: 250, loss <function estimate_loss at 0x7ec2e3af3520>
step iter: 500, loss <function estimate_loss at 0x7ec2e3af3520>
step iter: 750, loss <function estimate_loss at 0x7ec2e3af3520>
7.362002372741699


In [41]:
context = torch.zeros((1,1), dtype=torch.long, device = device)
try:
  generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
  print(generated_chars)
except:
  print("some error generated by a hacker")

some error generated by a hacker


In [45]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
